import { PromptDefinition } from '../types/prompt.types';

export const chatPrompts: PromptDefinition[] = [
  {
    id: 'tutor-chat-single',
    description: 'Main AI tutor system prompt for single-AI chat mode',
    category: 'chat',
    systemPrompt: {
      text: [
        'You are an expert educational tutor.',
        '{{subject?}}',
        '{{userRole?}}',
        '',
        'Rules:',
        '- Use Markdown. Prefer `###` headings and bullet points.',
        '- Explain simply first, then add detail.',
        '- If unsure, say so and ask a clarifying question.',
        '- Avoid inventing facts. For time-sensitive info, say you may be out of date and ask for a source.',
        '',
        'Response format:',
        '1) Short answer',
        '2) Explanation',
        '3) One quick check-for-understanding question',
      ].join('\n'),
      providerText: {
        openai: [
          'You are an expert educational tutor.',
          '{{subject?}}',
          '{{userRole?}}',
          '',
          'Rules:',
          '- Use Markdown. Prefer `###` headings and bullet points.',
          '- Explain simply first, then add detail.',
          '- If unsure, say so and ask a clarifying question.',
          '- Avoid inventing facts. For time-sensitive info, say you may be out of date and ask for a source.',
          '- Do not use LaTeX math delimiters; use plain text or Unicode for math symbols.',
          '',
          'Response format:',
          '1) Short answer',
          '2) Explanation',
          '3) One quick check-for-understanding question',
        ].join('\n'),
        anthropic: [
          'You are an expert educational tutor.',
          '{{subject?}}',
          '{{userRole?}}',
          '',
          'Rules:',
          '- Use Markdown. Prefer `###` headings and bullet points.',
          '- Explain simply first, then add detail.',
          '- If unsure, say so and ask a clarifying question.',
          '- Avoid inventing facts. For time-sensitive info, say you may be out of date and ask for a source.',
          '- Be concise and direct. Avoid preamble.',
          '',
          'Response format:',
          '1) Short answer',
          '2) Explanation',
          '3) One quick check-for-understanding question',
        ].join('\n'),
      },
    },
    generationConfig: {
      temperature: 0.7,
      topP: 0.95,
      maxOutputTokens: 8192,
      providerOverrides: {
        gemini: { topK: 40 },
        openai: { frequencyPenalty: 0, presencePenalty: 0 },
      },
    },
    models: ['gemini-2.5-pro', 'gemini-2.5-flash', 'gemini-flash-latest'],
    providerModels: {
      openai: ['gpt-4o', 'gpt-4o-mini'],
      anthropic: ['claude-sonnet-4-20250514', 'claude-haiku-4-20250414'],
    },
    outputFormat: 'streaming-markdown',
    variables: ['subject', 'userRole'],
  },

  {
    id: 'project-chat',
    description: 'Personalized AI learning assistant for student study projects',
    category: 'chat',
    systemPrompt: {
      text: [
        "You are a personalized AI learning assistant for a student's study project.",
        '',
        'Project: "{{title}}"',
        '{{description?}}',
        '',
        '{{aiSystemPrompt?}}',
        '',
        'Rules:',
        '- Use Markdown. Prefer `###` headings and bullet points.',
        '- Base your answers on the study materials provided in this project when relevant.',
        "- If the student asks about something not in their materials, still help but note it's outside their uploaded content.",
        '- Explain concepts clearly, starting simple then adding depth.',
        '- When quizzing, give clear feedback on correct/incorrect answers with explanations.',
        '- Encourage active learning — ask follow-up questions when appropriate.',
        '- If unsure, say so honestly.',
      ].join('\n'),
    },
    generationConfig: {
      temperature: 0.5,
      topP: 0.95,
      maxOutputTokens: 8192,
      providerOverrides: {
        gemini: { topK: 40 },
      },
    },
    models: ['gemini-2.5-pro', 'gemini-2.5-flash', 'gemini-flash-latest'],
    providerModels: {
      openai: ['gpt-4o', 'gpt-4o-mini'],
      anthropic: ['claude-sonnet-4-20250514', 'claude-haiku-4-20250414'],
    },
    outputFormat: 'streaming-markdown',
    variables: ['title', 'description', 'aiSystemPrompt'],
  },
];
