-- AlterTable
ALTER TABLE "students" ADD COLUMN     "academicLevel" TEXT,
ADD COLUMN     "address" TEXT,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "country" TEXT,
ADD COLUMN     "learningGoals" TEXT,
ADD COLUMN     "parentEmail" TEXT,
ADD COLUMN     "parentName" TEXT,
ADD COLUMN     "parentPhone" TEXT,
ADD COLUMN     "preferredSubjects" "Subject"[] DEFAULT ARRAY[]::"Subject"[],
ADD COLUMN     "profileCompleted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "state" TEXT,
ADD COLUMN     "timezone" TEXT;

-- AlterTable
ALTER TABLE "tutors" ADD COLUMN     "academicQualifications" JSONB,
ADD COLUMN     "address" TEXT,
ADD COLUMN     "areasOfExpertise" TEXT,
ADD COLUMN     "availabilitySchedule" JSONB,
ADD COLUMN     "bankAccountNumber" TEXT,
ADD COLUMN     "bankName" TEXT,
ADD COLUMN     "bankRoutingNumber" TEXT,
ADD COLUMN     "certificates" JSONB,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "country" TEXT,
ADD COLUMN     "dateOfBirth" TIMESTAMP(3),
ADD COLUMN     "languages" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "linkedinUrl" TEXT,
ADD COLUMN     "phoneNumber" TEXT,
ADD COLUMN     "profileCompleted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "publications" TEXT,
ADD COLUMN     "researchExperience" TEXT,
ADD COLUMN     "state" TEXT,
ADD COLUMN     "teachingPhilosophy" TEXT,
ADD COLUMN     "teachingStyle" TEXT,
ADD COLUMN     "timezone" TEXT,
ADD COLUMN     "totalHoursTaught" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalReviews" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalSessionsCompleted" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalStudentsTaught" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "verifiedAt" TIMESTAMP(3),
ADD COLUMN     "websiteUrl" TEXT,
ADD COLUMN     "workExperience" JSONB;
